### ISSUE TITLE
ProcessDataBlock script problem

### ISSUE THREAD

**Issue by pstepaniak** [bluesoft-rnd/aperte-workflow-core#167]
1. If you add a file script in ProcessDataBlock and an readOnly combobox an 'nill' error will be displayed for the user.
2. If you add a file script in ProcessDataBlock and an empty combobox, the combobox won't be visible for the user.

**Comment by pstepaniak** [comment]
Stacktrace for 2.:

SEVERE:  : only whitespace content allowed before start tag and not n (position: START_DOCUMENT seen n... @1:1)
com.thoughtworks.xstream.io.StreamException:  : only whitespace content allowed before start tag and not n (position: START_DOCUMENT seen n... @1:1)
        at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:78)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:137)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:130)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:109)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:94)
        at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:48)
        at com.thoughtworks.xstream.io.xml.XppDriver.createReader(XppDriver.java:44)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:853)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:845)
        at pl.net.bluesoft.rnd.pt.utils.xml.OXHelper.unmarshall(OXHelper.java:54)
        at pl.net.bluesoft.rnd.processtool.ui.basewidgets.editor.ProcessDataHierarchyEditor.processXml(ProcessDataHierarchyEditor.java:203)
        at pl.net.bluesoft.rnd.processtool.ui.basewidgets.editor.ProcessDataWidgetsDefinitionEditor.processXml(ProcessDataWidgetsDefinitionEditor.java:90)
        at pl.net.bluesoft.rnd.processtool.ui.basewidgets.editor.ProcessDataWidgetsDefinitionEditor.setPropertyDataSource(ProcessDataWidgetsDefinitionEditor.java:169)
        at org.aperteworkflow.editor.stepeditor.user.WidgetConfigFormFieldFactory.createBaseField(WidgetConfigFormFieldFactory.java:79)
        at org.aperteworkflow.editor.stepeditor.user.WidgetConfigFormFieldFactory.createField(WidgetConfigFormFieldFactory.java:24)
        at org.aperteworkflow.editor.ui.property.PropertiesPanel.refreshForm(PropertiesPanel.java:61)
        at org.aperteworkflow.editor.stepeditor.user.WidgetItemInStep.<init>(WidgetItemInStep.java:53)
        at org.aperteworkflow.editor.stepeditor.user.JSONHandler.analyzeNode(JSONHandler.java:119)
        at org.aperteworkflow.editor.stepeditor.user.JSONHandler.analyzeChildren(JSONHandler.java:107)
        at org.aperteworkflow.editor.stepeditor.user.JSONHandler.analyzeChildren(JSONHandler.java:108)
        at org.aperteworkflow.editor.stepeditor.user.JSONHandler.analyzeChildren(JSONHandler.java:108)
        at org.aperteworkflow.editor.stepeditor.user.JSONHandler.loadConfig(JSONHandler.java:63)
        at org.aperteworkflow.editor.stepeditor.user.UserStepEditorWindow.loadJSONConfig(UserStepEditorWindow.java:391)
        at org.aperteworkflow.editor.stepeditor.user.UserStepEditorWindow.init(UserStepEditorWindow.java:82)
        at org.aperteworkflow.editor.stepeditor.StepEditorApplication.refresh(StepEditorApplication.java:69)
        at org.aperteworkflow.editor.stepeditor.StepEditorApplication.handleParameters(StepEditorApplication.java:58)
        at com.vaadin.ui.Window.handleParameters(Window.java:511)
        at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:528)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at pl.net.bluesoft.rnd.processtool.plugins.PermissionFilter.doFilter(PermissionFilter.java:45)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:619)
Caused by: org.xmlpull.v1.XmlPullParserException: only whitespace content allowed before start tag and not n (position: START_DOCUMENT seen n... @1:1)
        at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1519)
        at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
        at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
        at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:63)
        ... 43 more
2012-05-30 10:31:12 org.jbpm.internal.log.Jdk14Log info
INFO: jBPM version info: library[4.4-SNAPSHOT], schema[null]

**Comment by pstepaniak** [comment]
Resolved https://github.com/pstepaniak/aperte-workflow-core/commit/a7fe19dfaf31a3dfede87e63fa19a623b2d4afa4
