### ISSUE TITLE
Groovy script problem

### ISSUE THREAD

**Issue by pstepaniak** [bluesoft-rnd/aperte-workflow-core#168]
You can't use the ItemElement class in Groovy script. An import doesn't help.

**Comment by pstepaniak** [comment]
Stacktrace:

SEVERE: Script error: <br/>
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 33: unable to resolve class ItemElement
 @ line 33, column 15.
                ItemElement item = A.getValues().get(i);
                 ^

1 error

```
    at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:296)
    at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:846)
    at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:519)
    at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:495)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:472)
```

**Comment by pstepaniak** [comment]
Fixed in:
https://github.com/pstepaniak/aperte-workflow-plugins/commit/555dd1369801b59ce3e2967274715ad9cc6b4681
