### ISSUE TITLE
Aperte Step Editor misleading logs

### ISSUE THREAD

**Issue by pstepaniak** [bluesoft-rnd/aperte-workflow-core#173]
If  you add to an empty step in Aperte Step Editor an Process Data Block you can see in logs a stacktrace. The Step Editor works fine, but the logs are very misleading.

**Comment by pstepaniak** [comment]
Stacktrace:
SEVERE:  : only whitespace content allowed before start tag and not n (position: START_DOCUMENT seen n... @1:1)
com.thoughtworks.xstream.io.StreamException:  : only whitespace content allowed before start tag and not n (position: START_DOCUMENT seen n... @1:1)
        at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:78)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:137)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:130)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:109)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:94)
        at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:48)
        at com.thoughtworks.xstream.io.xml.XppDriver.createReader(XppDriver.java:44)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:853)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:845)
        at pl.net.bluesoft.rnd.pt.utils.xml.OXHelper.unmarshall(OXHelper.java:59)
        at pl.net.bluesoft.rnd.processtool.ui.basewidgets.editor.ProcessDataHierarchyEditor.processXml(ProcessDataHierarchyEditor.java:203)
        at pl.net.bluesoft.rnd.processtool.ui.basewidgets.editor.ProcessDataWidgetsDefinitionEditor.processXml(ProcessDataWidgetsDefinitionEditor.java:90)
        at pl.net.bluesoft.rnd.processtool.ui.basewidgets.editor.ProcessDataWidgetsDefinitionEditor.setPropertyDataSource(ProcessDataWidgetsDefinitionEditor.java:169)
        at org.aperteworkflow.editor.stepeditor.user.WidgetConfigFormFieldFactory.createBaseField(WidgetConfigFormFieldFactory.java:79)
        at org.aperteworkflow.editor.stepeditor.user.WidgetConfigFormFieldFactory.createField(WidgetConfigFormFieldFactory.java:24)
        at org.aperteworkflow.editor.ui.property.PropertiesPanel.refreshForm(PropertiesPanel.java:61)
        at org.aperteworkflow.editor.stepeditor.user.WidgetItemInStep.<init>(WidgetItemInStep.java:53)
        at org.aperteworkflow.editor.stepeditor.user.TreeDropHandler.drop(TreeDropHandler.java:40)
        at com.vaadin.terminal.gwt.server.DragAndDropService.handleDropRequest(DragAndDropService.java:106)
        at com.vaadin.terminal.gwt.server.DragAndDropService.changeVariables(DragAndDropService.java:73)
        at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.changeVariables(AbstractCommunicationManager.java:1455)
        at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariableBurst(AbstractCommunicationManager.java:1399)
        at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariables(AbstractCommunicationManager.java:1318)
        at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.doHandleUidlRequest(AbstractCommunicationManager.java:763)
        at com.vaadin.terminal.gwt.server.CommunicationManager.handleUidlRequest(CommunicationManager.java:296)
        at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:501)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at pl.net.bluesoft.rnd.processtool.plugins.PermissionFilter.doFilter(PermissionFilter.java:45)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:619)
Caused by: org.xmlpull.v1.XmlPullParserException: only whitespace content allowed before start tag and not n (position: START_DOCUMENT seen n... @1:1)
        at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1519)
        at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
        at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
        at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:63)
        ... 42 more

**Comment by mmroczkowski** [comment]
Problem caused by null xml value when step is empty. Corrected by null check.
