### ISSUE TITLE
Activiti automatic step startup problem

### ISSUE THREAD

**Issue by pstepaniak** [bluesoft-rnd/aperte-workflow-core#180]
When an Activiti process starts with an automatic step an error occurs:

2012-06-13 15:34:18 org.activiti.engine.impl.interceptor.CommandContext close
SEVERE: Error while closing command context
java.lang.NullPointerException
        at org.aperteworkflow.ext.activiti.ActivitiStepAction.execute(ActivitiStepAction.java:97)
        at org.activiti.engine.impl.delegate.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:34)
        at org.activiti.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:37)
        at org.activiti.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:25)
        at org.activiti.engine.impl.bpmn.behavior.ServiceTaskJavaDelegateActivityBehavior.execute(ServiceTaskJavaDelegateActivityBehavior.java:49)
        at org.activiti.engine.impl.bpmn.behavior.ServiceTaskJavaDelegateActivityBehavior.execute(ServiceTaskJavaDelegateActivityBehavior.java:40)
(...)

**Comment by pstepaniak** [comment]
Resolved in:
https://github.com/pstepaniak/aperte-workflow-core/commit/ca34f73a664b8c1d490935ba2c2db07f5685f78d
