### ISSUE TITLE
User step not displaying

### ISSUE THREAD

**Issue by pstepaniak** [bluesoft-rnd/aperte-workflow-core#181]
When you deploy a process with user steps, and there will be no description of this step (in the 'State Configuration' tab) the step won't display - an error will be thrown:

SEVERE: null
java.lang.NullPointerException
        at pl.net.bluesoft.rnd.processtool.ui.process.ProcessDataPane.initLayout(ProcessDataPane.java:127)
        at pl.net.bluesoft.rnd.processtool.ui.process.ProcessDataPane.<init>(ProcessDataPane.java:72)
        at pl.net.bluesoft.rnd.processtool.ui.process.ProcessDataViewComponent.attachProcessDataPane(ProcessDataViewComponent.java:95)
        at pl.net.bluesoft.rnd.processtool.ui.activity.ActivityMainPane$3.render(ActivityMainPane.java:147)
        at pl.net.bluesoft.rnd.processtool.view.impl.BasicViewController.renderView(BasicViewController.java:91)
        at pl.net.bluesoft.rnd.processtool.view.impl.BasicViewController.displayView(BasicViewController.java:82)
        at pl.net.bluesoft.rnd.processtool.view.impl.BasicViewController.displayView(BasicViewController.java:55)

The reason is the value of the description field in the pt_process_state_config

**Comment by mmroczkowski** [comment]
Not reproductible in APW 2.0.
