### ISSUE TITLE
visibleLines

### ISSUE THREAD

**Issue by manowak** [bluesoft-rnd/aperte-workflow-core#196]
ProcessDataBlock-> FormWidgetElement->TextAreaWidget-> visibleLines -when is empty - Exception:

com.vaadin.data.Property$ConversionException: java.lang.reflect.InvocationTargetException

```
at com.vaadin.data.util.MethodProperty.convertValue(MethodProperty.java:697)

at com.vaadin.data.util.MethodProperty.setValue(MethodProperty.java:666)

at com.vaadin.ui.AbstractField.commit(AbstractField.java:258)

at com.vaadin.ui.Form.commit(Form.java:339)

at pl.net.bluesoft.rnd.processtool.ui.basewidgets.editor.WidgetPropertiesEditorFormComponent.commit(WidgetPropertiesEditorFormComponent.java:63)

at pl.net.bluesoft.rnd.processtool.ui.basewidgets.editor.WidgetPropertiesEditorFormComponent$1.buttonClick(WidgetPropertiesEditorFormComponent.java:49)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)

at java.lang.reflect.Method.invoke(Method.java:597)

at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:512)

at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:164)

at com.vaadin.ui.AbstractComponent.fireEvent(AbstractComponent.java:1219)

at com.vaadin.ui.Button.fireClick(Button.java:550)

at com.vaadin.ui.Button.changeVariables(Button.java:217)

at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.changeVariables(AbstractCommunicationManager.java:1455)

at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariableBurst(AbstractCommunicationManager.java:1399)

at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariables(AbstractCommunicationManager.java:1318)

at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.doHandleUidlRequest(AbstractCommunicationManager.java:763)

at com.vaadin.terminal.gwt.server.CommunicationManager.handleUidlRequest(CommunicationManager.java:296)

at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:501)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

at pl.net.bluesoft.rnd.processtool.plugins.PermissionFilter.doFilter(PermissionFilter.java:45)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)

at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)

at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)

at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)

at java.lang.Thread.run(Thread.java:619)
```

Caused by: java.lang.reflect.InvocationTargetException

```
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)

at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

at com.vaadin.data.util.MethodProperty.convertValue(MethodProperty.java:694)

... 36 more
```

Caused by: java.lang.NumberFormatException: For input string: ""

```
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)

at java.lang.Integer.parseInt(Integer.java:470)

at java.lang.Integer.<init>(Integer.java:660)

... 41 more
```

**Comment by mmroczkowski** [comment]
Not reproductible on apw 2.0, please confirm.
