### ISSUE TITLE
exception in Recent Tasks

### ISSUE THREAD

**Issue by lbortlik** [bluesoft-rnd/aperte-workflow-core#20]
Steps to reproduce:
- successful finish of sample process
- select my process in Recent Tasks.

An exception appears:
java.lang.NullPointerException
        at pl.net.bluesoft.rnd.processtool.ui.process.ProcessDataPane.initLayout(ProcessDataPane.java:125)
        at pl.net.bluesoft.rnd.processtool.ui.process.ProcessDataPane.<init>(ProcessDataPane.java:63)
        at pl.net.bluesoft.rnd.processtool.ui.activity.ActivityMainPane.displayProcessData(ActivityMainPane.java:160)
        at pl.net.bluesoft.rnd.processtool.ui.activity.ActivityMainPane.displayProcessData(ActivityMainPane.java:135)

**Comment by lbortlik** [comment]
path to sample process (on saffron):
/home/aperte/aperte-runtime/modeler-repo/Test/Test1.signavio.xml
