### ISSUE TITLE
Aperte Workflow DataSource

### ISSUE THREAD

**Issue by manowak** [bluesoft-rnd/aperte-workflow-core#201]
conf:
<Resource name="jdbc/aperte-workflow-ds" auth="Container" type="javax.sql.DataSource"
              maxActive="100" maxIdle="30" maxWait="10000"
              username="sa" password="" driverClassName="org.hsqldb.jdbcDriver"
              url="jdbc:hsqldb:${liferay.home}/data/hsql/aperte-workflow"
        />

cons:
2012-11-16 12:01:11 pl.net.bluesoft.rnd.processtool.plugins.osgi.PluginHelper ha
ndleProcessDeployment
SEVERE: Could not execute JDBC batch update
org.hibernate.exception.GenericJDBCException: Could not execute JDBC batch updat
e
        at org.hibernate.exception.SQLStateConverter.handledNonSpecificException
(SQLStateConverter.java:140)
        at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.j
ava:128)
        at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelp
er.java:66)
        at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:
275)
        at org.hibernate.jdbc.AbstractBatcher.prepareStatement(AbstractBatcher.j
ava:114)
        at org.hibernate.jdbc.AbstractBatcher.prepareStatement(AbstractBatcher.j
ava:109)
        at org.hibernate.jdbc.AbstractBatcher.prepareBatchStatement(AbstractBatc
her.java:244)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(Abstrac
tEntityPersister.java:2412)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(Abstrac
tEntityPersister.java:2875)
        at org.hibernate.action.EntityInsertAction.execute(EntityInsertAction.ja
va:79)
        at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:273)
        at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:265)

```
    at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:184)

    at org.hibernate.event.def.AbstractFlushingEventListener.performExecutio
```

ns(AbstractFlushingEventListener.java:321)
        at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlus
hEventListener.java:51)
        at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
        at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
        at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java
:133)
        at pl.net.bluesoft.rnd.pt.ext.jbpm.ProcessToolContextFactoryImpl.withPro
cessToolContextNonJta(ProcessToolContextFactoryImpl.java:84)
        at pl.net.bluesoft.rnd.pt.ext.jbpm.ProcessToolContextFactoryImpl.withPro
cessToolContext(ProcessToolContextFactoryImpl.java:60)
        at pl.net.bluesoft.rnd.pt.ext.jbpm.ProcessToolContextFactoryImpl.deployO
rUpdateProcessDefinition(ProcessToolContextFactoryImpl.java:169)
        at pl.net.bluesoft.rnd.pt.ext.jbpm.ProcessToolContextFactoryImpl.deployO
rUpdateProcessDefinition(ProcessToolContextFactoryImpl.java:243)
        at pl.net.bluesoft.rnd.processtool.plugins.ProcessToolRegistryImpl.deplo
yOrUpdateProcessDefinition(ProcessToolRegistryImpl.java:761)
        at pl.net.bluesoft.rnd.processtool.plugins.osgi.PluginHelper.handleProce
ssDeployment(PluginHelper.java:368)
        at pl.net.bluesoft.rnd.processtool.plugins.osgi.PluginHelper.processBund
leExtensions(PluginHelper.java:257)
        at pl.net.bluesoft.rnd.processtool.plugins.osgi.PluginHelper.installBund
les(PluginHelper.java:809)
        at pl.net.bluesoft.rnd.processtool.plugins.osgi.PluginHelper.installBund
les(PluginHelper.java:706)
        at pl.net.bluesoft.rnd.processtool.plugins.osgi.PluginHelper.scheduledBu
ndleInstall(PluginHelper.java:687)
        at pl.net.bluesoft.rnd.processtool.plugins.osgi.PluginHelper.access$200(
PluginHelper.java:51)
        at pl.net.bluesoft.rnd.processtool.plugins.osgi.PluginHelper$5.run(Plugi
nHelper.java:658)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:44
1)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(ScheduledThreadPoolExecutor.java:98)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:619)
Caused by: java.sql.BatchUpdateException: failed batch
        at org.hsqldb.jdbc.jdbcStatement.executeBatch(Unknown Source)
        at org.hsqldb.jdbc.jdbcPreparedStatement.executeBatch(Unknown Source)
        at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeBatch(Delegati
ngStatement.java:297)
        at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeBatch(Delegati
ngStatement.java:297)
        at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.jav
a:70)
        at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:
268)
        ... 34 more

**Comment by manowak** [comment]
Remove aperte-workflow.script

**Comment by kkolodziej** [comment]
From (aperte main folder)/data/hsql/
