### ISSUE TITLE
Aperte workflow 2.0 deployment in Jboss 7.1.1 is failing

### ISSUE THREAD

**Issue by sridhar1912** [bluesoft-rnd/aperte-workflow-core#217]
I am getting a 'UserTransaction not found' error when I try deploying Aperte Workflow 2.0 in Jboss AS 7.1.1 in '../standalone/deployments' directory.
I am using:
          JDK1.6.0_05
          Windows Vista Enterprise
          Jboss AS 7.1.1 Standalone
          Liferay 6.1 CE

My datasource configured in standalone.xml is 'java:/jdbc/aperte-workflow-ds', the same value I have configured in jboss-web.xml of aperteworkflow.war in 'jndi-name' property.

Please let me know where I am going wrong.
Following is the error I am getting:

08:41:59,049 INFO  [org.hibernate.util.NamingHelper](MSC service thread 1-2) JN
DI InitialContext properties:{}
08:41:59,439 SEVERE [pl.net.bluesoft.rnd.util.ProcessToolRegistryContextLoader](MSC service thread 1-2) Could not find UserTransaction in JNDI [UserTransaction
]: org.hibernate.TransactionException: Could not find UserTransaction in JNDI [U
serTransaction]
        at org.hibernate.transaction.JTATransactionFactory.getUserTransaction(JT
ATransactionFactory.java:173) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
        at org.hibernate.transaction.JTATransactionFactory.createTransaction(JTA
TransactionFactory.java:149) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
        at org.hibernate.jdbc.JDBCContext.getTransaction(JDBCContext.java:241) [
hibernate-core-3.6.10.Final.jar:3.6.10.Final]
        at org.hibernate.impl.SessionImpl.getTransaction(SessionImpl.java:1462)
[hibernate-core-3.6.10.Final.jar:3.6.10.Final]
        at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1472
) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
        at pl.net.bluesoft.rnd.processtool.plugins.ProcessToolRegistryImpl.updat
eCaches(ProcessToolRegistryImpl.java:891) [integration-2.0-RC1.jar:]
        at pl.net.bluesoft.rnd.processtool.plugins.ProcessToolRegistryImpl.<init

> (ProcessToolRegistryImpl.java:149) [integration-2.0-RC1.jar:]
>         at pl.net.bluesoft.rnd.util.ProcessToolRegistryContextLoader.contextInit
> ialized(ProcessToolRegistryContextLoader.java:21) [classes:]
>         at org.apache.catalina.core.StandardContext.contextListenerStart(Standar
> dContext.java:3392) [jbossweb-7.0.13.Final.jar:]
>         at org.apache.catalina.core.StandardContext.start(StandardContext.java:3
> 850) [jbossweb-7.0.13.Final.jar:]
>         at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentS
> ervice.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
>         at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(Se
> rviceControllerImpl.java:1811)
>         at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceCont
> rollerImpl.java:1746)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
> utor.java:885) [rt.jar:1.6.0_05]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
> .java:907) [rt.jar:1.6.0_05]
>         at java.lang.Thread.run(Thread.java:619) [rt.jar:1.6.0_05]
> Caused by: javax.naming.NameNotFoundException: UserTransaction -- service jboss.
> naming.context.java.UserTransaction
>         at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNaming
> Store.java:97)
>         at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:178)
>         at org.jboss.as.naming.InitialContext.lookup(InitialContext.java:113)
>         at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:214)
>         at javax.naming.InitialContext.lookup(InitialContext.java:392) [rt.jar:1
> .6.0_05]
>         at org.hibernate.transaction.JTATransactionFactory.getUserTransaction(JT
> ATransactionFactory.java:163) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
>         ... 15 more

**Comment by kkolodziej** [comment]
Acctually the jboss 7 is not supported  by apperte, but we would like add it to our list.  So i wrote a post on official aperte forum:
http://www.aperteworkflow.org/pl/forum/-/message_boards/view_message/16362
Who knows maybe someone already resolved this problem. 
Because we  still finishing 2.0 version(Documentation, news on forums etc.) we dont have much time, but we will keep you posted about our progress in this issue, on forum. So if you don't have account on our forum please create one. And stay tuned.

**Comment by Nanduyana** [comment]
Caused by: org.hibernate.TransactionException: Could not find UserTransaction in JNDI [java:jboss/UserTransaction]
        at org.hibernate.transaction.JTATransactionFactory.getUserTransaction(JTATransactionFactory.java:173) [hibernate-core-3.6.6.Final.jar:3.6.6.Final]
        at org.hibernate.transaction.JTATransactionFactory.createTransaction(JTATransactionFactory.java:149) [hibernate-core-3.6.6.Final.jar:3.6.6.Final]
        at org.hibernate.jdbc.JDBCContext.registerSynchronizationIfPossible(JDBCContext.java:213) [hibernate-core-3.6.6.Final.jar:3.6.6.Final]
Caused by: javax.naming.NameNotFoundException: UserTransaction [Root exception is java.lang.IllegalStateException: JBAS014237: Only session and message-drive
n beans with bean-managed transaction demarcation are allowed to access UserTransaction]
        at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:140)
        at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:81)
        at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:202)
        at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:179)
        at org.jboss.as.naming.InitialContext$DefaultInitialContext.lookup(InitialContext.java:235)
        at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:188)
        at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:184)
        at javax.naming.InitialContext.lookup(InitialContext.java:411) [rt.jar:1.7.0_67]
        at javax.naming.InitialContext.lookup(InitialContext.java:411) [rt.jar:1.7.0_67]
        at org.hibernate.transaction.JTATransactionFactory.getUserTransaction(JTATransactionFactory.java:163) [hibernate-core-3.6.6.Final.jar:3.6.6.Final]
        ... 143 more
Caused by: java.lang.IllegalStateException: JBAS014237: Only session and message-driven beans with bean-managed transaction demarcation are allowed to access
 UserTransaction
        at org.jboss.as.ejb3.component.allowedmethods.AllowedMethodsInformation.realCheckPermission(AllowedMethodsInformation.java:138) [wildfly-ejb3-8.1.0.F
inal.jar:8.1.0.Final]
        at org.jboss.as.ejb3.component.allowedmethods.AllowedMethodsInformation.checkAllowed(AllowedMethodsInformation.java:112) [wildfly-ejb3-8.1.0.Final.ja
r:8.1.0.Final]
        at org.jboss.as.ejb3.subsystem.EJB3UserTransactionAccessControlService$1.authorizeAccess(EJB3UserTransactionAccessControlService.java:53) [wildfly-ej
b3-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.txn.service.UserTransactionAccessControlService.authorizeAccess(UserTransactionAccessControlService.java:83)
        at org.jboss.as.txn.service.UserTransactionBindingService$1.getReference(UserTransactionBindingService.java:71)
        at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:131)

can some one please help us on this

**Comment by Nanduyana** [comment]
i am getting the above in wildfly with hibernate version  3.6.6 
Not able to find the jndi for UserTranasaction 
do we need any specific configuration for this in wildfly
