### ISSUE TITLE
Incorrect null date values handling in ProcessDataBlokWidget

### ISSUE THREAD

**Issue by zmalinowski** [bluesoft-rnd/aperte-workflow-core#24]
Empty fields are represented as "null" strings, which, in case of date fields, leads to:

java.lang.IllegalArgumentException: Cannot format given Object as a Date

when parser tries to parse provided date with date format.

**Comment by zmalinowski** [comment]
``` java
java.lang.NullPointerException: replacement
    at java.util.regex.Matcher.replaceFirst(Matcher.java:867)
    at java.lang.String.replaceFirst(String.java:2158)
    at pl.net.bluesoft.rnd.processtool.ui.basewidgets.ProcessDataBlockWidget$ComponentEvaluator.<init>(ProcessDataBlockWidget.java:116)
    at pl.net.bluesoft.rnd.processtool.ui.basewidgets.ProcessDataBlockWidget$2.<init>(ProcessDataBlockWidget.java:191)
    at pl.net.bluesoft.rnd.processtool.ui.basewidgets.ProcessDataBlockWidget.saveData(ProcessDataBlockWidget.java:191)
    at pl.net.bluesoft.rnd.processtool.ui.process.ProcessDataPane$2$1$1.run(ProcessDataPane.java:207)
    at pl.net.bluesoft.rnd.util.vaadin.VaadinExceptionHandler$Util.withErrorHandling(VaadinExceptionHandler.java:27)
    at pl.net.bluesoft.rnd.processtool.ui.process.ProcessDataPane$2$1.saveProcessData(ProcessDataPane.java:202)
    at pl.net.bluesoft.rnd.processtool.ui.buttons.StandardValidatingButton.onButtonPress(StandardValidatingButton.java:64)
    at pl.net.bluesoft.rnd.processtool.ui.process.ProcessDataPane$2.buttonClick(ProcessDataPane.java:199)
```
