### ISSUE TITLE
APERTE WORKFLOW 3.2, Tomcat Server is not starting

### ISSUE THREAD

**Issue by mytab2mendu** [bluesoft-rnd/aperte-workflow-core#261]
I just download APERTE WORKFLOW 3.2 and start the tomcat / bin/ startup.bat file and i'm getting bellow errors 

I'm new to APERTE WORKFLOW 3.2... pls help me.. any installation document.. 

error running recovery on resource 'jdbc/aperte-workflow-ds', resource marked as failed (background recoverer will retry recovery)
bitronix.tm.recovery.RecoveryException: cannot start recovery on a PoolingDataSource containing an XAPool of resource jdbc/aperte-workflow-ds with 0 connection(s) (0 still available) -failed-
    at bitronix.tm.resource.jdbc.PoolingDataSource.startRecovery(PoolingDataSource.java:288)
    at bitronix.tm.recovery.Recoverer.recover(Recoverer.java:258)
    at bitronix.tm.recovery.Recoverer.recoverAllResources(Recoverer.java:226)
    at bitronix.tm.recovery.Recoverer.run(Recoverer.java:142)
    at java.lang.Thread.run(Thread.java:745)
Caused by: bitronix.tm.internal.BitronixRuntimeException: incremental recovery failed when trying to acquire a connection from failed resource 'jdbc/aperte-workflow-ds'
    at bitronix.tm.resource.common.XAPool.getConnectionHandle(XAPool.java:103)
    at bitronix.tm.resource.jdbc.PoolingDataSource.startRecovery(PoolingDataSource.java:284)
    ... 4 more
Caused by: bitronix.tm.recovery.RecoveryException: cannot start recovery on a PoolingDataSource containing an XAPool of resource jdbc/aperte-workflow-ds with 0 connection(s) (0 still available)
    at bitronix.tm.resource.jdbc.PoolingDataSource.startRecovery(PoolingDataSource.java:288)
    at bitronix.tm.recovery.IncrementalRecoverer.recover(IncrementalRecoverer.java:61)
    at bitronix.tm.resource.common.XAPool.getConnectionHandle(XAPool.java:100)
    ... 5 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
    at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:138)
    at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
    at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
    at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
    at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
    at org.postgresql.Driver.makeConnection(Driver.java:410)
    at org.postgresql.Driver.connect(Driver.java:280)
    at java.sql.DriverManager.getConnection(DriverManager.java:571)
    at java.sql.DriverManager.getConnection(DriverManager.java:215)
    at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:99)
    at org.postgresql.xa.jdbc3.AbstractJdbc3XADataSource.getXAConnection(AbstractJdbc3XADataSource.java:54)
    at org.postgresql.xa.jdbc3.AbstractJdbc3XADataSource.getXAConnection(AbstractJdbc3XADataSource.java:39)
    at bitronix.tm.resource.jdbc.PoolingDataSource.createPooledConnection(PoolingDataSource.java:341)
    at bitronix.tm.resource.common.XAPool.createPooledObject(XAPool.java:283)
    at bitronix.tm.resource.common.XAPool.grow(XAPool.java:391)
    at bitronix.tm.resource.common.XAPool.getInPool(XAPool.java:371)
    at bitronix.tm.resource.common.XAPool.getConnectionHandle(XAPool.java:123)
    at bitronix.tm.resource.jdbc.PoolingDataSource.startRecovery(PoolingDataSource.java:284)
    ... 7 more
Caused by: java.net.ConnectException: Connection refused: connect
    at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at org.postgresql.core.PGStream.<init>(PGStream.java:60)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)

**Comment by tchaye59** [comment]
I have the same problem

**Comment by tchaye59** [comment]
Did you solve it?
