### ISSUE TITLE
Activiti process failing

### ISSUE THREAD

**Issue by ghost** [bluesoft-rnd/aperte-workflow-core#91]
When deploying activiti process (for example 'Liferay Symposium Submissions', but I also tried 'Reservation' and my custom process prepared in modeler) it deploys fine.
But when I try to start the process I get an exception "couldn't parse 'activitisample.bpmn20.xml': Content is not allowed in prolog.".
Here is the stacktrace:

<pre>

org.activiti.engine.ActivitiException: couldn't parse 'activitisample.bpmn20.xml': Content is not allowed in prolog.
    at org.activiti.engine.impl.util.xml.Parse.execute(Parse.java:136)
    at org.activiti.engine.impl.bpmn.parser.BpmnParse.execute(BpmnParse.java:189)
    at org.activiti.engine.impl.bpmn.deployer.BpmnDeployer.deploy(BpmnDeployer.java:81)
    at org.activiti.engine.impl.persistence.deploy.DeploymentCache.deploy(DeploymentCache.java:37)
    at org.activiti.engine.impl.persistence.deploy.DeploymentCache.resolveProcessDefinition(DeploymentCache.java:78)
    at org.activiti.engine.impl.persistence.deploy.DeploymentCache.findDeployedLatestProcessDefinitionByKey(DeploymentCache.java:64)
    at org.activiti.engine.impl.cmd.StartProcessInstanceCmd.execute(StartProcessInstanceCmd.java:58)
    at org.activiti.engine.impl.cmd.StartProcessInstanceCmd.execute(StartProcessInstanceCmd.java:31)
    at org.activiti.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:24)
    at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:42)
    at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)
    at org.activiti.engine.impl.RuntimeServiceImpl.startProcessInstanceByKey(RuntimeServiceImpl.java:53)
    at org.aperteworkflow.ext.activiti.ActivitiBpmSession.startProcessInstance(ActivitiBpmSession.java:452)
    at pl.net.bluesoft.rnd.processtool.bpm.impl.AbstractProcessToolSession.createProcessInstance(AbstractProcessToolSession.java:83)
    at pl.net.bluesoft.rnd.processtool.ui.newprocess.NewProcessExtendedPane$1$1.run(NewProcessExtendedPane.java:76)
    at org.aperteworkflow.util.vaadin.VaadinExceptionHandler$Util.withErrorHandling(VaadinExceptionHandler.java:27)
    at pl.net.bluesoft.rnd.processtool.ui.newprocess.NewProcessExtendedPane$1.buttonClick(NewProcessExtendedPane.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:512)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:164)
    at com.vaadin.ui.AbstractComponent.fireEvent(AbstractComponent.java:1219)
    at com.vaadin.ui.Button.fireClick(Button.java:550)
    at com.vaadin.ui.Button.changeVariables(Button.java:217)
    at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.changeVariables(AbstractCommunicationManager.java:1451)
    at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariableBurst(AbstractCommunicationManager.java:1399)
    at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariables(AbstractCommunicationManager.java:1318)
    at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.doHandleUidlRequest(AbstractCommunicationManager.java:763)
    at com.vaadin.terminal.gwt.server.PortletCommunicationManager.handleUidlRequest(PortletCommunicationManager.java:242)
    at com.vaadin.terminal.gwt.server.AbstractApplicationPortlet.handleRequest(AbstractApplicationPortlet.java:465)
    at org.aperteworkflow.util.vaadin.ProcessToolVaadinApplicationPortlet2.access$001(ProcessToolVaadinApplicationPortlet2.java:18)
    at org.aperteworkflow.util.vaadin.ProcessToolVaadinApplicationPortlet2$1.withContext(ProcessToolVaadinApplicationPortlet2.java:36)
    at org.aperteworkflow.ext.activiti.ActivitiContextFactoryImpl.withProcessToolContextNonJta(ActivitiContextFactoryImpl.java:62)
    at org.aperteworkflow.ext.activiti.ActivitiContextFactoryImpl.withProcessToolContext(ActivitiContextFactoryImpl.java:51)
    at pl.net.bluesoft.rnd.processtool.plugins.ProcessToolRegistryImpl.withProcessToolContext(ProcessToolRegistryImpl.java:374)
    at org.aperteworkflow.util.vaadin.ProcessToolVaadinApplicationPortlet2.handleRequest(ProcessToolVaadinApplicationPortlet2.java:29)
    at com.vaadin.terminal.gwt.server.AbstractApplicationPortlet.serveResource(AbstractApplicationPortlet.java:747)
    at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:119)
    at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
    at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:92)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        .... [many more lines]
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1234)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:525)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:392)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
    at org.activiti.engine.impl.util.xml.Parse.execute(Parse.java:133)
</pre>

**Comment by ghost** [comment]
Issue caused by old postgresql driver bundled with aperteworkflow. It wasn't compatible with my 9.1 database in bytea handling.
Upgrading jdbc driver to version 9.1 resolved the issue.
