### ISSUE TITLE
Problem with removing plugins from Control Panel

### ISSUE THREAD

**Issue by ghost** [bluesoft-rnd/aperte-workflow-core#93]
When i try to uninstall plugin in Control Panel i get an exception:

<pre>
Caused by: pl.net.bluesoft.rnd.processtool.plugins.PluginManagementException: pl.net.bluesoft.rnd.processtool.plugins.PluginManagementException: Failed to remove file: file:///home/mwysocki_bls/servers/aperteworkflow-activiti/osgi-plugins/reservation.jar
    at pl.net.bluesoft.rnd.processtool.plugins.osgi.PluginHelper.uninstallPlugin(PluginHelper.java:929)
    at pl.net.bluesoft.rnd.processtool.ui.plugins.PluginsManagerPane$5.run(PluginsManagerPane.java:125)
    at org.aperteworkflow.util.vaadin.VaadinUtility$3.buttonClick(VaadinUtility.java:340)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:512)
    ... 185 more
Caused by: pl.net.bluesoft.rnd.processtool.plugins.PluginManagementException: Failed to remove file: file:///home/mwysocki_bls/servers/aperteworkflow-activiti/osgi-plugins/reservation.jar
    at pl.net.bluesoft.rnd.processtool.plugins.osgi.PluginHelper.uninstallPlugin(PluginHelper.java:923)
    ... 192 more
</pre>

**Comment by tlipski** [comment]
it happens probably due to some race condition - but it shouldn't happen. Please look into it.

**Comment by tlipski** [comment]
Some kind solution of course would be http://docs.oracle.com/javase/1.4.2/docs/api/java/io/File.html#deleteOnExit() on this file, but it is somewhat unreliable (what if JVM dies from kill -9?)

**Comment by ghost** [comment]
I tried scheduling deletion every 10 seconds, renaming/moving, and it didn't work.
deleteOnExit didn't work even when server was stopped with regular kill or using bin/shutdown.sh
I found some advices to try it with Java 7, but nothing has changed.

What about copying bundles from osgi-plugins to installed-osgi-plugins and loading them from the latter?
Then you can easilly remove them from osgi-plugins so they won't be installed after restart.
